<?php

declare(strict_types=1);

$profiles = [
    'provisioning' => [
        'inventory',
        'system_metrics',
        'ifspeed',
        'fortinet_discovery',
        'mikrotik_discovery',
        'autonomous_enterprise',
        'loaded_mibs',
        'huawei_optical',
        'optical_dom',
        'environmental',
        'gpon',
        'dahua_discovery',
    ],
    'network' => [
        'inventory',
        'system_metrics',
        'interface_discovery',
        'ifspeed',
        'interface_stats',
        'bridge_port_speed',
        'huawei_interface_discovery',
        'cisco_interface_discovery',
        'zte_interface_discovery',
        'alcatel_interface_discovery',
        'raisecom_interface_discovery',
        'fortinet_discovery',
        'mikrotik_discovery',
        'autonomous_enterprise',
        'loaded_mibs',
        'huawei_optical',
        'optical_dom',
        'optical_power_with_thresholds',
        'environmental',
        'gpon',
        'dahua_discovery',
    ],
    'system' => [
        'inventory',
        'system_metrics',
        'universal_system',
        'cpu_usage',
        'memory_usage',
        'fortinet_discovery',
        'mikrotik_discovery',
        'autonomous_enterprise',
        'loaded_mibs',
        'environmental',
        'custom_metrics',
        'printer',
    ],
    'printer' => [
        'inventory',
        'printer',
        'system_metrics',
        'cpu_usage',
        'memory_usage',
    ],
    'cctv' => [
        'inventory',
        'dahua_discovery',
    ],
    'router_switch' => [
        'inventory',
        'system_metrics',
        'interface_discovery',
        'ifspeed',
        'interface_stats',
        'optical_dom',
        'environmental',
        'cpu_usage',
        'memory_usage',
        'fortinet_discovery',
        'mikrotik_discovery',
        'autonomous_enterprise',
        'loaded_mibs',
    ],
    'olt' => [
        'inventory',
        'system_metrics',
        'olt',
        'gpon',
        'optical_dom',
    ],
    'rectifier' => [
        'inventory',
        'system_metrics',
        'rectifier',
        'environmental',
    ],
    'full' => [
        'inventory',
        'system_metrics',
        'universal_system',
        'cpu_usage',
        'memory_usage',
        'printer',
        'interface_discovery',
        'ifspeed',
        'interface_stats',
        'bridge_port_speed',
        'cisco_interface_discovery',
        'huawei_interface_discovery',
        'zte_interface_discovery',
        'alcatel_interface_discovery',
        'raisecom_interface_discovery',
        'fortinet_discovery',
        'mikrotik_discovery',
        'autonomous_enterprise',
        'loaded_mibs',
        'F5InterfaceDiscovery',
        'F5VirtualServerDiscovery',
        'F5PoolDiscovery',
        'F5PoolMemberDiscovery',
        'dahua_discovery',
        'huawei_optical',
        'optical_dom',
        'optical_power_with_thresholds',
        'environmental',
        'gpon',
        'rectifier',
        'olt',
        'custom_metrics',
        'comprehensive_oid',
    ],
];

$descriptions = [
    'provisioning' => 'Fast production scan for basic device identity: inventory, system metrics, interface speeds, and optics.',
    'network' => 'Full network scan: interfaces, traffic counters, bridge ports, vendor-specific modules, optical DOM, and GPON.',
    'system' => 'Full system/server scan: SNMPv2 system fields, host resources, CPU, memory, uptime, environmental sensors, and custom metrics.',
    'printer' => 'Targeted printer scan: identity, health, supplies, trays, alerts, basic CPU/memory, and uptime.',
    'cctv' => 'Targeted CCTV/NVR scan: device identity, camera layout, channels, storage volumes, video detection, and network settings.',
    'router_switch' => 'Router & Switch (Physical Port) scan: Bandwidth, ifHCInOctets, ifHCOutOctets, ifOperStatus, inUsage, outUsage, ifSpeed, Host Alive, Optical Rx/Tx Power, Temperature, CPU, Memory, Fan.',
    'olt' => 'OLT scan: Host Alive availability status, GPON interfaces, and optical DOM.',
    'rectifier' => 'Rectifier & Power System scan: AC Fail, AC Phase Volt, Batt Current/Voltage/Fuse, Door Open, e0 management port, System Power, Load Current/Fuse, Rectifail.',
    'full' => 'Comprehensive scan: runs all available modules with bounded discovery limits. Deep subtree walks require DISCOVERY_COMPREHENSIVE_FULL_WALK=true.',
];

return [
    'profile' => (string) env('DISCOVERY_PROFILE', 'provisioning'),
    'profiles' => $profiles,
    'descriptions' => $descriptions,
    'enabled_modules' => env_list('DISCOVERY_ENABLED_MODULES'),
    'disabled_modules' => env_list('DISCOVERY_DISABLED_MODULES'),
    'log_module_timings' => env_bool('DISCOVERY_LOG_MODULE_TIMINGS', false),
];
